name: fire_playground
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  firebase_analytics: ^11.3.6
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  intl: ^0.20.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
