// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtP9oVYKV1022y3j4qcVOFpjdOLhikP_4',
    appId: '1:610457094774:web:94df1a6204b5cdb6fb6d57',
    messagingSenderId: '610457094774',
    projectId: 'fire-playground-cae3a',
    authDomain: 'fire-playground-cae3a.firebaseapp.com',
    storageBucket: 'fire-playground-cae3a.firebasestorage.app',
    measurementId: 'G-T8N6T52MYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzvriOX3erFCPkPpCq3uv1974gleXWptg',
    appId: '1:610457094774:android:199372051648ed8efb6d57',
    messagingSenderId: '610457094774',
    projectId: 'fire-playground-cae3a',
    storageBucket: 'fire-playground-cae3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK-piq5gmuqtzW9raD6Ykiuj4qd_fFEZg',
    appId: '1:610457094774:ios:d57c990bf7d2b842fb6d57',
    messagingSenderId: '610457094774',
    projectId: 'fire-playground-cae3a',
    storageBucket: 'fire-playground-cae3a.firebasestorage.app',
    iosBundleId: 'com.example.firePlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK-piq5gmuqtzW9raD6Ykiuj4qd_fFEZg',
    appId: '1:610457094774:ios:d57c990bf7d2b842fb6d57',
    messagingSenderId: '610457094774',
    projectId: 'fire-playground-cae3a',
    storageBucket: 'fire-playground-cae3a.firebasestorage.app',
    iosBundleId: 'com.example.firePlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtP9oVYKV1022y3j4qcVOFpjdOLhikP_4',
    appId: '1:610457094774:web:7816d6c4d99c5878fb6d57',
    messagingSenderId: '610457094774',
    projectId: 'fire-playground-cae3a',
    authDomain: 'fire-playground-cae3a.firebaseapp.com',
    storageBucket: 'fire-playground-cae3a.firebasestorage.app',
    measurementId: 'G-3KLJMQR3TT',
  );
}
